fastlane_version '2.157'
default_platform :ios

platform :ios do
  # Unit Test Lane
  desc 'Runs unit tests only'
  lane :run_unit_tests do |options|
    scan(
      scheme: "Psotify",
      clean: options[:clean],
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution],
      only_testing: "PsotifyTests"
    )
  end

  desc 'Builds the IPA and uploads to App Center'
  lane :build_and_upload do
    gym(
      scheme: "Psotify",
      output_directory: "Build",
      output_name: "Psotify.ipa"
    )

    appcenter_upload(
      api_token: ENV["APP_CENTER_API_TOKEN"],
      owner_name: "Kaan Turan",
      app_name: "Psotify",
      ipa: "Build/Psotify.ipa"
    )
  end
end
