fastlane_version '2.157'
default_platform :ios

platform :ios do
  desc 'Builds project and executes unit tests'
  lane :unit_test do |options|
    scan(
      scheme: "Psotify",
      clean: options[:clean]
    )
  end

  desc 'Builds the IPA and uploads to App Center'
  lane :appcenter_upload do
    gym(
      project: "Psotify.xcodeproj",
      scheme: "Psotify",
      output_directory: "Build",
      output_name: "Psotify.ipa"
    )

    appcenter_upload(
      api_token: ENV["APP_CENTER_API_TOKEN"],
      owner_name: "Kaan Turan",
      app_name: "Psotify",
      ipa: "Build/Psotify.ipa"
    )
  end
end
