name: Continuous Delivery

on:
  push:
    branches:
      - feature/CI-CD
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build IPA and Upload to App Center
        run: |
          # Build the IPA and upload it to App Center with automatic signing
          xcodebuild -project Psotify.xcodeproj -scheme Psotify -sdk iphoneos -configuration Release -archivePath $PWD/build/Psotify.xcarchive clean archive -allowProvisioningUpdates
          bundle exec fastlane build_and_upload
        env:
          APP_CENTER_API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}
