name: Pull Request

on:
  pull_request:
    branches:
      - psotify/Phase-1/CI-CD-integration
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Run Unit Tests
        run: bundle exec fastlane unit_test